### ISSUE TITLE
can it?

### ISSUE THREAD

**Issue by martindurant** [agstephens/can-it-kerchunk#1]
:)

Please let me know how testing has gone for you.

Note that there is more care taken for CF times in both the single-HDF and dataset combine steps now.

**Comment by agstephens** [comment]
Hi @martindurant, thanks for getting in touch. We are currently immersed in other things so it's been a while since I looked at kerchunk. However, it is firmly in our sights to work with this year. I'll update you when we have more feedback. Great to hear that the code is evolving. Thanks

**Comment by agstephens** [comment]
Hi @martindurant, we have finally found some time to get working on this stuff. We are interested in pursuing:
- access to files on disk (by clients that read disk directly)
- access to files through an S3 interface (but not needing to replicate the data).

We are putting some tooling here, because we'll need a framework to generate many (probably millions) of kerchunk files:

https://github.com/cedadev/kerchunk-tools

It is all looking very promising at the moment. Thanks for creating these building blocks for us to build up from :-)
